# Generated by Django 4.2.7 on 2023-11-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_faculties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculties',
            new_name='Faculty',
        ),
    ]
